import pandas as pd
import yfinance as yf

class YFinanceClient:
    """Manages transactional text requests mapping stock and commodity market indicators."""
    
    @staticmethod
    def fetch_daily_close(ticker: str, label: str, period: str = "6mo", tail_len: int = 90) -> pd.DataFrame:
        """Downloads historical charts from Yahoo Finance and normalizes column shapes cleanly."""
        try:
            print(f"[YFinance] Downloading fresh daily data arrays for symbol token: {ticker}")
            raw_data = yf.download(ticker, period=period, auto_adjust=True)
            if not raw_data.empty:
                # Handle MultiIndex levels generated by newer yfinance software updates
                if isinstance(raw_data.columns, pd.MultiIndex):
                    raw_data.columns = raw_data.columns.get_level_values(0)
                    
                df = raw_data[['Close']].copy().reset_index()
                df.columns = ['Date', label]  
                return df.sort_values("Date").set_index('Date').tail(tail_len)
        except Exception as e:
            print(f"[YFinance Warning] Ingestion failed for symbol {ticker}: {str(e)}")
            
        # Standard fallback matrix generator to guarantee UI layout persistence if network hits gaps
        dates = pd.date_range(end=pd.Timestamp.now(), periods=tail_len, freq='D')
        fallback_val = 75.0 if "oil" in label.lower() else (18000.0 if "nasdaq" in label.lower() else 5200.0)
        return pd.DataFrame({"Date": dates, label: [fallback_val] * tail_len}).set_index("Date")
